route:
  receiver: webhook
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 1m

receivers:
  - name: webhook
    webhook_configs:
      - url: "http://webhook:5001/webhook"
        send_resolved: true
